# Generated by Django 4.2.1 on 2023-11-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book_desc',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book_image',
        ),
        migrations.RemoveField(
            model_name='review',
            name='book_title',
        ),
    ]
